### ISSUE TITLE
Does this module still work with the version 3.0.4 of react-babylonjs?

### ISSUE THREAD

**Issue by j-tdk** [hookex/react-babylon-spring#1]
Hello, when I try to integrate these modul into my react-babylonjs (version 3.0.4) project the spring animation doesn't update on each render. It updates just on hover. What do I wrong or does the component did not work with react-babylonjs in the current version 3.0.4? Can you please update the examples with the current version of react-babylonjs? 

Here is an example:
https://codesandbox.io/s/angry-dhawan-pjfsz?file=/src/App.js

**Comment by brianzinn** [comment]
hi @j-tdk - thanks for reporting!  It's a breaking change in 'react-babylonjs'.  Has to do with a breaking changed introduced on the public reference and this part of the code:
```javascript
const host = createHost(primitives, {
  applyAnimatedValues: applyInitialPropsToInstance,
})
```
I'll fix this breaking change in `react-babylonjs` by introducing a property on the public object to access handlers for property changes, which I was hoping to avoid.  I'll continue on the other issue you have created.
